import type { ThemeConfig } from "@/lib/types"

// ============================================
// THEME PRESET DEFINITIONS
// ============================================

export interface ThemePreset {
  id: string
  name: string
  description: string
  preview: {
    primary: string
    accent: string
    background: string
  }
  config: ThemeConfig
}

// --------------------------------------------
// 1. Lexintel Default
// --------------------------------------------
const lexintelDefault: ThemePreset = {
  id: "lexintel-default",
  name: "Lexintel Default",
  description:
    "The original monochrome palette. Clean black-on-cream with DM Sans body type and DM Serif Display headings.",
  preview: {
    primary: "#111111",
    accent: "#111111",
    background: "#FAFAF8",
  },
  config: {
    light: {
      background: "#FAFAF8",
      foreground: "#111111",
      primary: "#111111",
      "primary-foreground": "#FAFAF8",
      secondary: "#F5F5F3",
      "secondary-foreground": "#111111",
      accent: "#111111",
      "accent-foreground": "#FFFFFF",
      muted: "#F5F5F3",
      "muted-foreground": "#999999",
      destructive: "#DC2626",
      "destructive-foreground": "#FFFFFF",
      card: "#FFFFFF",
      "card-foreground": "#111111",
      popover: "#FFFFFF",
      "popover-foreground": "#111111",
      border: "#E5E4E2",
      input: "#E5E4E2",
      ring: "#111111",
      "chart-1": "#111111",
      "chart-2": "#444444",
      "chart-3": "#777777",
      "chart-4": "#AAAAAA",
      "chart-5": "#DDDDDD",
      "sidebar-background": "#F5F4F2",
      "sidebar-foreground": "#111111",
      "sidebar-accent": "#FFFFFF",
      "sidebar-border": "#E5E4E2",
      "primary-light": "#222222",
      "accent-hover": "#2A2A2A",
      "accent-muted": "#F5F5F3",
      surface: "#F5F4F2",
      "surface-hover": "#EDECEB",
      "border-strong": "#D1D0CE",
      success: "#16A34A",
      "success-light": "#F0FDF4",
      warning: "#CA8A04",
      "warning-light": "#FEFCE8",
    },
    dark: {
      background: "#0A0A0A",
      foreground: "#FAFAF8",
      primary: "#FAFAF8",
      "primary-foreground": "#111111",
      secondary: "#1A1A1A",
      "secondary-foreground": "#FAFAF8",
      accent: "#FAFAF8",
      "accent-foreground": "#111111",
      muted: "#1A1A1A",
      "muted-foreground": "#666666",
      destructive: "#EF4444",
      "destructive-foreground": "#FFFFFF",
      card: "#141414",
      "card-foreground": "#FAFAF8",
      popover: "#141414",
      "popover-foreground": "#FAFAF8",
      border: "#2A2A2A",
      input: "#2A2A2A",
      ring: "#FAFAF8",
      "chart-1": "#FAFAF8",
      "chart-2": "#CCCCCC",
      "chart-3": "#999999",
      "chart-4": "#666666",
      "chart-5": "#333333",
      "sidebar-background": "#0F0F0F",
      "sidebar-foreground": "#FAFAF8",
      "sidebar-accent": "#1A1A1A",
      "sidebar-border": "#2A2A2A",
      "primary-light": "#DDDDDD",
      "accent-hover": "#CCCCCC",
      "accent-muted": "#1A1A1A",
      surface: "#141414",
      "surface-hover": "#1E1E1E",
      "border-strong": "#3A3A3A",
      success: "#22C55E",
      "success-light": "#052E16",
      warning: "#EAB308",
      "warning-light": "#422006",
    },
    typography: {
      "font-sans": "DM Sans",
      "font-display": "DM Serif Display",
      "font-mono": "JetBrains Mono",
    },
    layout: {
      "radius-sm": "0.375rem",
      "radius-md": "0.5rem",
      "radius-lg": "0.75rem",
      "radius-xl": "1rem",
    },
    shadows: {
      color: "#000000",
      opacity: "0.04",
      blur: "12px",
      spread: "0px",
      "offset-x": "0px",
      "offset-y": "4px",
    },
  },
}

// --------------------------------------------
// 2. Corporate Navy
// --------------------------------------------
const corporateNavy: ThemePreset = {
  id: "corporate-navy",
  name: "Corporate Navy",
  description:
    "Authoritative navy blue with gold accents. Playfair Display headlines convey tradition and trust.",
  preview: {
    primary: "#1a2744",
    accent: "#c9a84c",
    background: "#F8F9FB",
  },
  config: {
    light: {
      background: "#F8F9FB",
      foreground: "#1a2744",
      primary: "#1a2744",
      "primary-foreground": "#FFFFFF",
      secondary: "#EEF1F6",
      "secondary-foreground": "#1a2744",
      accent: "#c9a84c",
      "accent-foreground": "#1a2744",
      muted: "#EEF1F6",
      "muted-foreground": "#6B7A94",
      destructive: "#DC2626",
      "destructive-foreground": "#FFFFFF",
      card: "#FFFFFF",
      "card-foreground": "#1a2744",
      popover: "#FFFFFF",
      "popover-foreground": "#1a2744",
      border: "#D8DDE6",
      input: "#D8DDE6",
      ring: "#c9a84c",
      "chart-1": "#1a2744",
      "chart-2": "#2e4268",
      "chart-3": "#c9a84c",
      "chart-4": "#6B7A94",
      "chart-5": "#D8DDE6",
      "sidebar-background": "#F0F2F7",
      "sidebar-foreground": "#1a2744",
      "sidebar-accent": "#FFFFFF",
      "sidebar-border": "#D8DDE6",
      "primary-light": "#2e4268",
      "accent-hover": "#b8973e",
      "accent-muted": "#F5F0E2",
      surface: "#F0F2F7",
      "surface-hover": "#E4E8F0",
      "border-strong": "#B8C0D0",
      success: "#16A34A",
      "success-light": "#F0FDF4",
      warning: "#CA8A04",
      "warning-light": "#FEFCE8",
    },
    dark: {
      background: "#0C1220",
      foreground: "#E2E8F0",
      primary: "#E2E8F0",
      "primary-foreground": "#1a2744",
      secondary: "#162035",
      "secondary-foreground": "#E2E8F0",
      accent: "#c9a84c",
      "accent-foreground": "#0C1220",
      muted: "#162035",
      "muted-foreground": "#7B8BA4",
      destructive: "#EF4444",
      "destructive-foreground": "#FFFFFF",
      card: "#131D30",
      "card-foreground": "#E2E8F0",
      popover: "#131D30",
      "popover-foreground": "#E2E8F0",
      border: "#243352",
      input: "#243352",
      ring: "#c9a84c",
      "chart-1": "#c9a84c",
      "chart-2": "#E2E8F0",
      "chart-3": "#7B8BA4",
      "chart-4": "#4A5E7A",
      "chart-5": "#243352",
      "sidebar-background": "#0A0F1A",
      "sidebar-foreground": "#E2E8F0",
      "sidebar-accent": "#162035",
      "sidebar-border": "#243352",
      "primary-light": "#A8B8D0",
      "accent-hover": "#D4B85E",
      "accent-muted": "#1E2A40",
      surface: "#131D30",
      "surface-hover": "#1A2740",
      "border-strong": "#344868",
      success: "#22C55E",
      "success-light": "#052E16",
      warning: "#EAB308",
      "warning-light": "#422006",
    },
    typography: {
      "font-sans": "Inter",
      "font-display": "Playfair Display",
      "font-mono": "JetBrains Mono",
    },
    layout: {
      "radius-sm": "0.25rem",
      "radius-md": "0.375rem",
      "radius-lg": "0.5rem",
      "radius-xl": "0.75rem",
    },
    shadows: {
      color: "#1a2744",
      opacity: "0.06",
      blur: "16px",
      spread: "0px",
      "offset-x": "0px",
      "offset-y": "4px",
    },
  },
}

// --------------------------------------------
// 3. Modern Slate
// --------------------------------------------
const modernSlate: ThemePreset = {
  id: "modern-slate",
  name: "Modern Slate",
  description:
    "Cool slate grays with vibrant teal accents. Inter typeface for a clean, contemporary feel.",
  preview: {
    primary: "#334155",
    accent: "#0d9488",
    background: "#F8FAFC",
  },
  config: {
    light: {
      background: "#F8FAFC",
      foreground: "#0F172A",
      primary: "#334155",
      "primary-foreground": "#FFFFFF",
      secondary: "#F1F5F9",
      "secondary-foreground": "#334155",
      accent: "#0d9488",
      "accent-foreground": "#FFFFFF",
      muted: "#F1F5F9",
      "muted-foreground": "#94A3B8",
      destructive: "#DC2626",
      "destructive-foreground": "#FFFFFF",
      card: "#FFFFFF",
      "card-foreground": "#0F172A",
      popover: "#FFFFFF",
      "popover-foreground": "#0F172A",
      border: "#E2E8F0",
      input: "#E2E8F0",
      ring: "#0d9488",
      "chart-1": "#0d9488",
      "chart-2": "#334155",
      "chart-3": "#06B6D4",
      "chart-4": "#94A3B8",
      "chart-5": "#E2E8F0",
      "sidebar-background": "#F1F5F9",
      "sidebar-foreground": "#334155",
      "sidebar-accent": "#FFFFFF",
      "sidebar-border": "#E2E8F0",
      "primary-light": "#475569",
      "accent-hover": "#0F766E",
      "accent-muted": "#CCFBF1",
      surface: "#F1F5F9",
      "surface-hover": "#E2E8F0",
      "border-strong": "#CBD5E1",
      success: "#16A34A",
      "success-light": "#F0FDF4",
      warning: "#CA8A04",
      "warning-light": "#FEFCE8",
    },
    dark: {
      background: "#0F172A",
      foreground: "#F1F5F9",
      primary: "#F1F5F9",
      "primary-foreground": "#334155",
      secondary: "#1E293B",
      "secondary-foreground": "#F1F5F9",
      accent: "#2DD4BF",
      "accent-foreground": "#0F172A",
      muted: "#1E293B",
      "muted-foreground": "#64748B",
      destructive: "#EF4444",
      "destructive-foreground": "#FFFFFF",
      card: "#1E293B",
      "card-foreground": "#F1F5F9",
      popover: "#1E293B",
      "popover-foreground": "#F1F5F9",
      border: "#334155",
      input: "#334155",
      ring: "#2DD4BF",
      "chart-1": "#2DD4BF",
      "chart-2": "#F1F5F9",
      "chart-3": "#64748B",
      "chart-4": "#475569",
      "chart-5": "#334155",
      "sidebar-background": "#0B1121",
      "sidebar-foreground": "#F1F5F9",
      "sidebar-accent": "#1E293B",
      "sidebar-border": "#334155",
      "primary-light": "#CBD5E1",
      "accent-hover": "#5EEAD4",
      "accent-muted": "#1A2E3B",
      surface: "#1E293B",
      "surface-hover": "#293548",
      "border-strong": "#475569",
      success: "#22C55E",
      "success-light": "#052E16",
      warning: "#EAB308",
      "warning-light": "#422006",
    },
    typography: {
      "font-sans": "Inter",
      "font-display": "Inter",
      "font-mono": "JetBrains Mono",
    },
    layout: {
      "radius-sm": "0.375rem",
      "radius-md": "0.5rem",
      "radius-lg": "0.75rem",
      "radius-xl": "1rem",
    },
    shadows: {
      color: "#334155",
      opacity: "0.05",
      blur: "12px",
      spread: "0px",
      "offset-x": "0px",
      "offset-y": "2px",
    },
  },
}

// --------------------------------------------
// 4. Warm Counsel
// --------------------------------------------
const warmCounsel: ThemePreset = {
  id: "warm-counsel",
  name: "Warm Counsel",
  description:
    "Earthy stone and amber tones on a warm cream background. Lora serif for a welcoming, approachable tone.",
  preview: {
    primary: "#44403c",
    accent: "#d97706",
    background: "#faf8f5",
  },
  config: {
    light: {
      background: "#faf8f5",
      foreground: "#292524",
      primary: "#44403c",
      "primary-foreground": "#FAFAF8",
      secondary: "#F5F0EB",
      "secondary-foreground": "#44403c",
      accent: "#d97706",
      "accent-foreground": "#FFFFFF",
      muted: "#F5F0EB",
      "muted-foreground": "#A8A29E",
      destructive: "#DC2626",
      "destructive-foreground": "#FFFFFF",
      card: "#FFFFFE",
      "card-foreground": "#292524",
      popover: "#FFFFFE",
      "popover-foreground": "#292524",
      border: "#E7E0D8",
      input: "#E7E0D8",
      ring: "#d97706",
      "chart-1": "#d97706",
      "chart-2": "#44403c",
      "chart-3": "#B45309",
      "chart-4": "#A8A29E",
      "chart-5": "#E7E0D8",
      "sidebar-background": "#F3EDE6",
      "sidebar-foreground": "#44403c",
      "sidebar-accent": "#FFFFFE",
      "sidebar-border": "#E7E0D8",
      "primary-light": "#57534E",
      "accent-hover": "#B45309",
      "accent-muted": "#FEF3C7",
      surface: "#F3EDE6",
      "surface-hover": "#EAE2D8",
      "border-strong": "#D6CBC0",
      success: "#16A34A",
      "success-light": "#F0FDF4",
      warning: "#CA8A04",
      "warning-light": "#FEFCE8",
    },
    dark: {
      background: "#1C1917",
      foreground: "#F5F0EB",
      primary: "#F5F0EB",
      "primary-foreground": "#44403c",
      secondary: "#292524",
      "secondary-foreground": "#F5F0EB",
      accent: "#F59E0B",
      "accent-foreground": "#1C1917",
      muted: "#292524",
      "muted-foreground": "#78716C",
      destructive: "#EF4444",
      "destructive-foreground": "#FFFFFF",
      card: "#231F1D",
      "card-foreground": "#F5F0EB",
      popover: "#231F1D",
      "popover-foreground": "#F5F0EB",
      border: "#3D3834",
      input: "#3D3834",
      ring: "#F59E0B",
      "chart-1": "#F59E0B",
      "chart-2": "#F5F0EB",
      "chart-3": "#78716C",
      "chart-4": "#57534E",
      "chart-5": "#3D3834",
      "sidebar-background": "#171412",
      "sidebar-foreground": "#F5F0EB",
      "sidebar-accent": "#292524",
      "sidebar-border": "#3D3834",
      "primary-light": "#D6D3D1",
      "accent-hover": "#FBBF24",
      "accent-muted": "#3A2A14",
      surface: "#231F1D",
      "surface-hover": "#2E2926",
      "border-strong": "#524D48",
      success: "#22C55E",
      "success-light": "#052E16",
      warning: "#EAB308",
      "warning-light": "#422006",
    },
    typography: {
      "font-sans": "Lora",
      "font-display": "Lora",
      "font-mono": "JetBrains Mono",
    },
    layout: {
      "radius-sm": "0.375rem",
      "radius-md": "0.5rem",
      "radius-lg": "0.625rem",
      "radius-xl": "0.875rem",
    },
    shadows: {
      color: "#44403c",
      opacity: "0.05",
      blur: "14px",
      spread: "0px",
      "offset-x": "0px",
      "offset-y": "4px",
    },
  },
}

// --------------------------------------------
// 5. Pacific Blue
// --------------------------------------------
const pacificBlue: ThemePreset = {
  id: "pacific-blue",
  name: "Pacific Blue",
  description:
    "Bold blue primary with cool gray neutrals. Open Sans provides excellent readability across all sizes.",
  preview: {
    primary: "#1e40af",
    accent: "#3B82F6",
    background: "#F9FAFB",
  },
  config: {
    light: {
      background: "#F9FAFB",
      foreground: "#111827",
      primary: "#1e40af",
      "primary-foreground": "#FFFFFF",
      secondary: "#F3F4F6",
      "secondary-foreground": "#1F2937",
      accent: "#3B82F6",
      "accent-foreground": "#FFFFFF",
      muted: "#F3F4F6",
      "muted-foreground": "#9CA3AF",
      destructive: "#DC2626",
      "destructive-foreground": "#FFFFFF",
      card: "#FFFFFF",
      "card-foreground": "#111827",
      popover: "#FFFFFF",
      "popover-foreground": "#111827",
      border: "#E5E7EB",
      input: "#E5E7EB",
      ring: "#1e40af",
      "chart-1": "#1e40af",
      "chart-2": "#3B82F6",
      "chart-3": "#60A5FA",
      "chart-4": "#9CA3AF",
      "chart-5": "#E5E7EB",
      "sidebar-background": "#F3F4F6",
      "sidebar-foreground": "#1F2937",
      "sidebar-accent": "#FFFFFF",
      "sidebar-border": "#E5E7EB",
      "primary-light": "#2563EB",
      "accent-hover": "#2563EB",
      "accent-muted": "#DBEAFE",
      surface: "#F3F4F6",
      "surface-hover": "#E5E7EB",
      "border-strong": "#D1D5DB",
      success: "#16A34A",
      "success-light": "#F0FDF4",
      warning: "#CA8A04",
      "warning-light": "#FEFCE8",
    },
    dark: {
      background: "#0B0F19",
      foreground: "#F3F4F6",
      primary: "#F3F4F6",
      "primary-foreground": "#1e40af",
      secondary: "#1F2937",
      "secondary-foreground": "#F3F4F6",
      accent: "#60A5FA",
      "accent-foreground": "#0B0F19",
      muted: "#1F2937",
      "muted-foreground": "#6B7280",
      destructive: "#EF4444",
      "destructive-foreground": "#FFFFFF",
      card: "#111827",
      "card-foreground": "#F3F4F6",
      popover: "#111827",
      "popover-foreground": "#F3F4F6",
      border: "#374151",
      input: "#374151",
      ring: "#60A5FA",
      "chart-1": "#60A5FA",
      "chart-2": "#F3F4F6",
      "chart-3": "#6B7280",
      "chart-4": "#4B5563",
      "chart-5": "#374151",
      "sidebar-background": "#070B14",
      "sidebar-foreground": "#F3F4F6",
      "sidebar-accent": "#1F2937",
      "sidebar-border": "#374151",
      "primary-light": "#93C5FD",
      "accent-hover": "#93C5FD",
      "accent-muted": "#172554",
      surface: "#111827",
      "surface-hover": "#1C2536",
      "border-strong": "#4B5563",
      success: "#22C55E",
      "success-light": "#052E16",
      warning: "#EAB308",
      "warning-light": "#422006",
    },
    typography: {
      "font-sans": "Open Sans",
      "font-display": "Open Sans",
      "font-mono": "JetBrains Mono",
    },
    layout: {
      "radius-sm": "0.375rem",
      "radius-md": "0.5rem",
      "radius-lg": "0.75rem",
      "radius-xl": "1rem",
    },
    shadows: {
      color: "#1e40af",
      opacity: "0.04",
      blur: "12px",
      spread: "0px",
      "offset-x": "0px",
      "offset-y": "3px",
    },
  },
}

// --------------------------------------------
// 6. Emerald & Ivory
// --------------------------------------------
const emeraldIvory: ThemePreset = {
  id: "emerald-ivory",
  name: "Emerald & Ivory",
  description:
    "Deep forest green on ivory with a gold ring accent. Merriweather serif for a distinguished, literary quality.",
  preview: {
    primary: "#166534",
    accent: "#d4a853",
    background: "#fffff5",
  },
  config: {
    light: {
      background: "#fffff5",
      foreground: "#14532D",
      primary: "#166534",
      "primary-foreground": "#FFFFFF",
      secondary: "#F0F7F0",
      "secondary-foreground": "#166534",
      accent: "#d4a853",
      "accent-foreground": "#14532D",
      muted: "#F0F7F0",
      "muted-foreground": "#6B8F71",
      destructive: "#DC2626",
      "destructive-foreground": "#FFFFFF",
      card: "#FEFFFE",
      "card-foreground": "#14532D",
      popover: "#FEFFFE",
      "popover-foreground": "#14532D",
      border: "#D5E5D5",
      input: "#D5E5D5",
      ring: "#d4a853",
      "chart-1": "#166534",
      "chart-2": "#d4a853",
      "chart-3": "#22C55E",
      "chart-4": "#6B8F71",
      "chart-5": "#D5E5D5",
      "sidebar-background": "#EBF4EB",
      "sidebar-foreground": "#166534",
      "sidebar-accent": "#FEFFFE",
      "sidebar-border": "#D5E5D5",
      "primary-light": "#15803D",
      "accent-hover": "#C49640",
      "accent-muted": "#FDF6E3",
      surface: "#EBF4EB",
      "surface-hover": "#DDEEDD",
      "border-strong": "#B8D4B8",
      success: "#16A34A",
      "success-light": "#F0FDF4",
      warning: "#CA8A04",
      "warning-light": "#FEFCE8",
    },
    dark: {
      background: "#0A1A0E",
      foreground: "#E8F5E8",
      primary: "#E8F5E8",
      "primary-foreground": "#166534",
      secondary: "#142A18",
      "secondary-foreground": "#E8F5E8",
      accent: "#d4a853",
      "accent-foreground": "#0A1A0E",
      muted: "#142A18",
      "muted-foreground": "#5E8A64",
      destructive: "#EF4444",
      "destructive-foreground": "#FFFFFF",
      card: "#112416",
      "card-foreground": "#E8F5E8",
      popover: "#112416",
      "popover-foreground": "#E8F5E8",
      border: "#1E3A24",
      input: "#1E3A24",
      ring: "#d4a853",
      "chart-1": "#d4a853",
      "chart-2": "#E8F5E8",
      "chart-3": "#5E8A64",
      "chart-4": "#3A6B42",
      "chart-5": "#1E3A24",
      "sidebar-background": "#071408",
      "sidebar-foreground": "#E8F5E8",
      "sidebar-accent": "#142A18",
      "sidebar-border": "#1E3A24",
      "primary-light": "#A7D4A7",
      "accent-hover": "#E0BA6A",
      "accent-muted": "#2A2410",
      surface: "#112416",
      "surface-hover": "#183020",
      "border-strong": "#2E5034",
      success: "#22C55E",
      "success-light": "#052E16",
      warning: "#EAB308",
      "warning-light": "#422006",
    },
    typography: {
      "font-sans": "Merriweather",
      "font-display": "Merriweather",
      "font-mono": "JetBrains Mono",
    },
    layout: {
      "radius-sm": "0.25rem",
      "radius-md": "0.375rem",
      "radius-lg": "0.5rem",
      "radius-xl": "0.75rem",
    },
    shadows: {
      color: "#166534",
      opacity: "0.05",
      blur: "14px",
      spread: "0px",
      "offset-x": "0px",
      "offset-y": "4px",
    },
  },
}

// --------------------------------------------
// 7. Minimal Charcoal
// --------------------------------------------
const minimalCharcoal: ThemePreset = {
  id: "minimal-charcoal",
  name: "Minimal Charcoal",
  description:
    "Near-black on pure white for maximum contrast. Space Grotesk provides a sharp, modern geometric feel.",
  preview: {
    primary: "#18181b",
    accent: "#18181b",
    background: "#FFFFFF",
  },
  config: {
    light: {
      background: "#FFFFFF",
      foreground: "#18181b",
      primary: "#18181b",
      "primary-foreground": "#FFFFFF",
      secondary: "#F4F4F5",
      "secondary-foreground": "#18181b",
      accent: "#18181b",
      "accent-foreground": "#FFFFFF",
      muted: "#F4F4F5",
      "muted-foreground": "#A1A1AA",
      destructive: "#DC2626",
      "destructive-foreground": "#FFFFFF",
      card: "#FFFFFF",
      "card-foreground": "#18181b",
      popover: "#FFFFFF",
      "popover-foreground": "#18181b",
      border: "#E4E4E7",
      input: "#E4E4E7",
      ring: "#18181b",
      "chart-1": "#18181b",
      "chart-2": "#3F3F46",
      "chart-3": "#71717A",
      "chart-4": "#A1A1AA",
      "chart-5": "#E4E4E7",
      "sidebar-background": "#FAFAFA",
      "sidebar-foreground": "#18181b",
      "sidebar-accent": "#FFFFFF",
      "sidebar-border": "#E4E4E7",
      "primary-light": "#27272A",
      "accent-hover": "#3F3F46",
      "accent-muted": "#F4F4F5",
      surface: "#FAFAFA",
      "surface-hover": "#F4F4F5",
      "border-strong": "#D4D4D8",
      success: "#16A34A",
      "success-light": "#F0FDF4",
      warning: "#CA8A04",
      "warning-light": "#FEFCE8",
    },
    dark: {
      background: "#09090B",
      foreground: "#FAFAFA",
      primary: "#FAFAFA",
      "primary-foreground": "#18181b",
      secondary: "#18181b",
      "secondary-foreground": "#FAFAFA",
      accent: "#FAFAFA",
      "accent-foreground": "#18181b",
      muted: "#18181b",
      "muted-foreground": "#71717A",
      destructive: "#EF4444",
      "destructive-foreground": "#FFFFFF",
      card: "#111113",
      "card-foreground": "#FAFAFA",
      popover: "#111113",
      "popover-foreground": "#FAFAFA",
      border: "#27272A",
      input: "#27272A",
      ring: "#FAFAFA",
      "chart-1": "#FAFAFA",
      "chart-2": "#D4D4D8",
      "chart-3": "#A1A1AA",
      "chart-4": "#71717A",
      "chart-5": "#3F3F46",
      "sidebar-background": "#060608",
      "sidebar-foreground": "#FAFAFA",
      "sidebar-accent": "#18181b",
      "sidebar-border": "#27272A",
      "primary-light": "#D4D4D8",
      "accent-hover": "#E4E4E7",
      "accent-muted": "#18181b",
      surface: "#111113",
      "surface-hover": "#1C1C1F",
      "border-strong": "#3F3F46",
      success: "#22C55E",
      "success-light": "#052E16",
      warning: "#EAB308",
      "warning-light": "#422006",
    },
    typography: {
      "font-sans": "Space Grotesk",
      "font-display": "Space Grotesk",
      "font-mono": "JetBrains Mono",
    },
    layout: {
      "radius-sm": "0.25rem",
      "radius-md": "0.375rem",
      "radius-lg": "0.5rem",
      "radius-xl": "0.75rem",
    },
    shadows: {
      color: "#000000",
      opacity: "0.03",
      blur: "10px",
      spread: "0px",
      "offset-x": "0px",
      "offset-y": "2px",
    },
  },
}

// --------------------------------------------
// 8. Burgundy Classic
// --------------------------------------------
const burgundyClassic: ThemePreset = {
  id: "burgundy-classic",
  name: "Burgundy Classic",
  description:
    "Rich wine reds on warm stone with copper accents. Crimson Text serif evokes old-world legal gravitas.",
  preview: {
    primary: "#7f1d1d",
    accent: "#b87333",
    background: "#faf5f0",
  },
  config: {
    light: {
      background: "#faf5f0",
      foreground: "#450A0A",
      primary: "#7f1d1d",
      "primary-foreground": "#FFFFFF",
      secondary: "#F5ECE4",
      "secondary-foreground": "#7f1d1d",
      accent: "#b87333",
      "accent-foreground": "#FFFFFF",
      muted: "#F5ECE4",
      "muted-foreground": "#A68A76",
      destructive: "#DC2626",
      "destructive-foreground": "#FFFFFF",
      card: "#FFFCF8",
      "card-foreground": "#450A0A",
      popover: "#FFFCF8",
      "popover-foreground": "#450A0A",
      border: "#E8D8CA",
      input: "#E8D8CA",
      ring: "#b87333",
      "chart-1": "#7f1d1d",
      "chart-2": "#b87333",
      "chart-3": "#991B1B",
      "chart-4": "#A68A76",
      "chart-5": "#E8D8CA",
      "sidebar-background": "#F0E6DA",
      "sidebar-foreground": "#7f1d1d",
      "sidebar-accent": "#FFFCF8",
      "sidebar-border": "#E8D8CA",
      "primary-light": "#991B1B",
      "accent-hover": "#A66528",
      "accent-muted": "#FDF0E0",
      surface: "#F0E6DA",
      "surface-hover": "#E6D8C8",
      "border-strong": "#D4C0AE",
      success: "#16A34A",
      "success-light": "#F0FDF4",
      warning: "#CA8A04",
      "warning-light": "#FEFCE8",
    },
    dark: {
      background: "#1A0C0C",
      foreground: "#F5ECE4",
      primary: "#F5ECE4",
      "primary-foreground": "#7f1d1d",
      secondary: "#2A1414",
      "secondary-foreground": "#F5ECE4",
      accent: "#D4944E",
      "accent-foreground": "#1A0C0C",
      muted: "#2A1414",
      "muted-foreground": "#8A6A5A",
      destructive: "#EF4444",
      "destructive-foreground": "#FFFFFF",
      card: "#221010",
      "card-foreground": "#F5ECE4",
      popover: "#221010",
      "popover-foreground": "#F5ECE4",
      border: "#3D1E1E",
      input: "#3D1E1E",
      ring: "#D4944E",
      "chart-1": "#D4944E",
      "chart-2": "#F5ECE4",
      "chart-3": "#8A6A5A",
      "chart-4": "#5A3A2A",
      "chart-5": "#3D1E1E",
      "sidebar-background": "#140808",
      "sidebar-foreground": "#F5ECE4",
      "sidebar-accent": "#2A1414",
      "sidebar-border": "#3D1E1E",
      "primary-light": "#D4B8A8",
      "accent-hover": "#E0A862",
      "accent-muted": "#2E1A10",
      surface: "#221010",
      "surface-hover": "#2E1818",
      "border-strong": "#523030",
      success: "#22C55E",
      "success-light": "#052E16",
      warning: "#EAB308",
      "warning-light": "#422006",
    },
    typography: {
      "font-sans": "Crimson Text",
      "font-display": "Crimson Text",
      "font-mono": "JetBrains Mono",
    },
    layout: {
      "radius-sm": "0.25rem",
      "radius-md": "0.375rem",
      "radius-lg": "0.5rem",
      "radius-xl": "0.75rem",
    },
    shadows: {
      color: "#7f1d1d",
      opacity: "0.06",
      blur: "16px",
      spread: "0px",
      "offset-x": "0px",
      "offset-y": "4px",
    },
  },
}

// ============================================
// EXPORTS
// ============================================

/** All curated theme presets in display order. */
export const THEME_PRESETS: ThemePreset[] = [
  lexintelDefault,
  corporateNavy,
  modernSlate,
  warmCounsel,
  pacificBlue,
  emeraldIvory,
  minimalCharcoal,
  burgundyClassic,
]

/** Look up a preset by its slug (id). */
export const PRESET_MAP: Record<string, ThemePreset> = Object.fromEntries(
  THEME_PRESETS.map((preset) => [preset.id, preset]),
)
